name: Gradle Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: var
      name: Setup variables
      run: echo ::set-output name=commit_hash::${GITHUB_SHA:0:7}
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use gradle cache for faster builds
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: Build with Gradle
      run: ./gradlew build
      env:
        HW_VERSION: git-${{ steps.var.outputs.commit_hash }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: heatwave ${{ steps.var.outputs.commit_hash }}
        path: build/libs
        
